---
title: "git bundle-uri"
date: 2022-03-08T09:30:25+08:00
draft: true
---



[RFC Patch] git bundle-uri

[0/25] coverletter
------------------


https://public-inbox.org/git/pull.1160.git.1645641063.gitgitgadget@gmail.com/ 

 * Bundle URIs work for full and partial clones.

 * Bundle URIs can assist with git fetch in addition to git clone.

 * Users can set up bundle servers independent of the remote Git server if
   they specify the bundle URI via a --bundle-uri argument.


The general breakdown is as follows:

 * Patch 1 adds documentation for the feature in its entirety.

 * Patches 2-14 add the ability to run ‘git clone --bundle-uri=’

 * Patches 15-17 add bundle fetches to ‘git fetch’ calls

 * Patches 18-25 add a new ‘features’ capability that allows a server to
   advertise bundle URIs (and in the future, other features).


In addition, the Azure Storage accounts are available in different regions:

 * East US: https://gitbundleserver.z13.web.core.windows.net
 * West US: https://gitbundleserverwestus.z22.web.core.windows.net
 * Europe: https://gitbundleservereurope.z6.web.core.windows.net
 * East Asia: https://gitbundleservereastasia.z7.web.core.windows.net
 * South Asia: https://gitbundleserversouthasia.z23.web.core.windows.net
 * Australia: https://gitbundleserveraustralia.z26.web.core.windows.net

To test this RFC against these servers, choose your $org/$repo to clone and
your region's bundle server $url and run

$ git clone --bundle-uri=$url/$org/$repo/ https://github.com/$org/$repo


Here is a potential plan for splitting this RFC into digestible pieces that
can be reviewed in sequence:

*   Update the git bundle create command to take a --filter option, allowing
    bundles to store packfiles restricted to an object filter. This is
    necessary for using bundle URIs to benefit partial clones. 
    (让bundle支持--filter)

*   Integrate bundle URIs into git clone with a --bundle-uri option. This
    will include the full understanding of a table of contents, but will not
    integrate with git fetch or allow the server to advertise URIs. 
+
    (让git clone支持--bundle-uri选项， 但是不提供fetch的支持或者server端的URIs广播)

*   Integrate bundle URIs into git fetch, triggered by config values that
    are set during git clone if the server indicates that the bundle
    strategy works for fetches.
+
    （根据git-clone过程中设置的config values，支持git-fetch）

*   Create a new "recommended features" capability in protocol v2 where the
    server can recommend features such as bundle URIs, partial clone, and
    sparse-checkout. These features will be extremely limited in scope and
    blocked by opt-in config options. The design for this portion could be
    replaced by a "bundle-uri" capability that only advertises bundle URIs
    and no other information.
+
   （实现临时"recommended features" capability， 最终用"bundle-uri"替换）


[01/25] documentation
---------------------

Goal:
~~~~~

* poor network connectivity to the origin server

* heavy users: CI Bbuild farms

* reducing the load on the origin server

Server Requirment:

* HTTP（S） GET requests currently supported

* authentication requirements of the requests with the aim of triggering the configured 
credential helper for secure access.

* 200 OK response and with forms:

    ** 1. bundle version >= 2 (if only one bundle on remote CDN)
    ** A plain-text file(tableContents) that is parsable using Git's config file parser.  This file describes one or more bundles that are accessible from other URIs. (need to parse the text and download multiple bundles)

Table of contents format:
~~~~~~~~~~~~~~~~~~~~~~~~~

* parseable using Git's config parser: key/value

* bundle.tableOfContents.version: 1

* bundle.tableOfContents.forFetch: true/false; if true, the bundles is for fetch, if false, the bundle is for clone（prohibit excess data downloads）


* bundle.<id>.uri: This string value is the URI for downloading bundle `<id>`

* bundle.<id>.timestamp:: (Optional) This value is the number of seconds since Unix epoch(UTC) that this bundle was created

* bundle.<id>.requires:  (Optional) When present, the server is indicating that this bundle contains a thin packfile. If the client does not have all necessary objects to unbundle this packfile, then the client can download the bundle with the `requires` ID and try again. (Note: it may be beneficial to allow the server to specify multiple `requires` bundles.)

* bundle.<id>.filter: (Optional) This string value represents an object filter that 
should also appear in the header of this bundle. The server uses this value to differentiate different kinds of bundles from which the client can choose those that match their object filters.

Advertising bundle URIs:
~~~~~~~~~~~~~~~~~~~~~~~~

* 通过能力广播， 可以让用户无感的使用这个特性（不需要在clone时指定--bundle-uri）
* 扩展 v2协议， 在能力中新增bundle uris
* client可以根据广播的bundle uris, 选择哪些bundle uri可能获取更低的下载延迟（`在codeup上支持地域？ 或者我们默认就支持就近， 创建多个CDN， 解决了跨地域下载延时的问题？ `）
* server运维者负责决定， 是否多个uri要比单个地理分布的uri更好。


Cloning with bundle Uris:
~~~~~~~~~~~~~~~~~~~~~~~~

1. clone with the `--bundle-uri` or the client discovers a bundle URI that was advertised by server.

2. The client downloads the file at the bundle URI.  If it is a bundle, then it is unbundled with the refs being stored in `refs/bundle/*`.

3. If the file is instead a table of contents, then the bundles with matching `filter` settings are sorted by `timestamp` (if present), and the most-recent bundle is downloaded.

4. If the current bundle header mentions negative commid OIDs that are not in the object database, then download the `requires` bundle and try again. (里面提到的 `nagative` is "-" 应该是代表提交的prerequisite)

5. After inspecting a bundle with no negative commit OIDs (or all OIDs are
   already in the object database somehow), then unbundle all of the
   bundles in reverse order, placing references within `refs/bundle/*`.

6. The client performs a fetch negotiation with the origin server, using
   the `refs/bundle/*` references as `have`s and the server's ref
   advertisement as `want`s. This results in a pack-file containing the
   remaining objects requested by the clone but not in the bundles.

7. Note that during a clone we expect that all bundles will be required. The
client could be extended to download all bundles in parallel, though they
need to be unbundled in the correct order. （`can it recovery by a normal way under a failure?`）

8. If a table of contents is used and it contains
`bundle.tableOfContents.forFetch = true`, then the client can store a
config value indicating to reuse this URI for later `git fetch` commands.
In this case, the client will also want to store the maximum timestamp of
a downloaded bundle.

Fetching with bundle Uris:
~~~~~~~~~~~~~~~~~~~~~~~~~~

1. The fetch operation follows the same procedure to download bundles from a
table of contents (although we do _not_ want to use parallel downloads
here). We expect that the process will end because all negative commit
OIDs in a thin bundle are already in the object database.（`嗯。make sense`）

2. A further optimization is that the client can avoid downloading any
bundles if their timestamps are not larger than the stored timestamp.
After fetching new bundles, this local timestamp value is updated. （`嗯。make sense`）

Choices for Bundle Server Organization
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Bundles can have whatever name the server desires. This name could refer
  to immutable data by using a hash of the bundle contents. However, this
  means that a new URI will be needed after every update of the content.
  This might be acceptable if the server is advertising the URI (and the
  server is aware of new bundles being generated) but would not be
  ergonomic for users using the command line option. （`我觉得应该保留核心的config，
  把这类信息放入到/info目录下，防止配置膨胀`）

* If the server intends to only serve full clones, then the advertised URI
  could be a bundle file without a filter that is updated at some cadence. (`没错`)

* If the server intends to serve clones, but wants clients to choose full
  or blobless partial clones, then the server can use a table of contents
  that lists two non-thin bundles and the client chooses between them only
  by the `bundle.<id>.filter` values. （`没错`）

* If the server intends to serve fetches, then it can use a table of
  contents to advertise a list of bundles that are updated regularly. The
  most recent bundles could be generated on short intervals, such as hourly.
  These small bundles could be merged together at some rate, such as 24
  hourly bundles merging into a single daily bundle. At some point, it may
  be beneficial to create a bundle that stores the majority of the history,
  such as all data older than 30 days. （`与codeup目前备份策略大体相同`）

进展
--

*【2022.3.8】目前Avar和Derrick分别有自己的RFC实现， 他们决定开个视频会议讨论这个问题。

  